### ISSUE TITLE
Add information to paging errors

### ISSUE THREAD

**Issue by dmfenton** [koopjs/koop-agol#24]
error.code =  server status code
error.request = page requested
error.response = server message
error.message = explanation (e.g. failed to cache the data)

error.response will need to be trimmed to a reasonable number of characters. Otherwise when the web adaptor fails we will be sending back lots of html.

@benheb you will want to watch this as it will likely affect the composer activity panel.

**Comment by chelm** [comment]
@dmfenton how's this? http://koop.dc.esri.com/agol/arcgis/a577a18778454cee88863f14fd608c6b/14

**Comment by dmfenton** [comment]
doesn't make sense to nest the error under generating

**Comment by dmfenton** [comment]
thinking about this more, status should probably change to 'failed' when the error payload is present

**Comment by chelm** [comment]
@dmfenton - k well the changes to that are more far reaching. They have implication to in the UI and deeper into the controller. I'm tempted to get what we have now on to production then revamp the entire "processing" work flow in koop.

**Comment by dmfenton** [comment]
Agree with those priorities

**Comment by chelm** [comment]
@dmfenton but yes I agree that the status should have more "states" - processing, generating, and error. We should design what we want and build it in the sprint

**Comment by dmfenton** [comment]
:+1:

**Comment by dmfenton** [comment]
This is done
