### ISSUE TITLE
Errors should be normalized and in the requested MIME-Type format

### ISSUE THREAD

**Issue by ajturner** [koopjs/koop-agol#32]
Requesting 

`http://firstmap.delaware.opendata.arcgis.com/datasets/5d1d1faf58344909b36b14b6be2f0748_0.csv?url_only=true`

starts with `{"status":"processing","processing_time":13840.153,"count":0}`, and then after some error [responds with plain text `Could not create export, missing data`](https://github.com/Esri/koop-agol/blob/43bb540e32b3579205e88d9a95c3824fa1065c21/controller/index.js#L522)

/cc @dmfenton

**Comment by dmfenton** [comment]
We should take this as an opportunity to refactor status messages throughout all of Koop. Not just any one provider.

**Comment by jwieringa** [comment]
All error messages being returned in JSON is not a bug, it is done on purpose. We can discuss why and the problems we solved by doing this.

**Comment by ajturner** [comment]
@jwieringa you mean that "All error messages _not_ being returned in JSON is not a bug"?

**Comment by dmfenton** [comment]
This is done. If we find cases where I missed something we can log new bugs.
