### ISSUE TITLE
If WKID for download is 4236 or 10200 delete from cache key

### ISSUE THREAD

**Issue by dmfenton** [koopjs/koop-agol#41]
If we use these in cache keys, it's going to mean that all existing downloads generated with these spatial references will be ignored.

**Comment by chelm** [comment]
Hmm. So currently we dont pass in the wkid via the querystring. It gets pulled from the service automatically and is not used in the cache key thing. 

This is changing so that all exports will support using outSR from the querystring. I'll parse the outSR param and remove it if its in a whitelist of projections. 

Good call.

**Comment by dmfenton** [comment]
Oh weird. But does that mean we might serve some  other projection when we want WGS84?

**Comment by chelm** [comment]
How so? Projections are moving to an on-demand feature. Everything by default will serve wgs84. If the user wants a different projection they specify a valid outSR param in the querystring (wkid string, wkt string, or a valid object, etc). If these are determined to be a web merc or wgs84 proj then they are removed the WGS84 is served.

**Comment by dmfenton** [comment]
Let's say that today I request Dataset 123 that has projection 999 and the cache key is 123.

After the update, I request Dataset 123 in projection 4326 and 4326 is whitelisted. The cache key will still be 123 and I will get a download in projection 999.

Am I wrong?

**Comment by chelm** [comment]
true dat, until the cache is expired. So for non hosted not a big deal, but for for hosted would need to manually drop. we'll need to expire / clear the file export caches.

**Comment by dmfenton** [comment]
I think you're saying that we should just drop everything. And I, unfortunately, agree.

**Comment by dmfenton** [comment]
Actually, all hosted is in web merc right?

**Comment by dmfenton** [comment]
@astauffer can you weigh in?

**Comment by jgravois** [comment]
im not @astauffer, but its possible for customers to publish hosted feature services in custom projections from ArcGIS Desktop.

**Comment by astauffer** [comment]
drop it all

**Comment by dmfenton** [comment]
OK I think we have a conclusion

**Comment by chelm** [comment]
burn it all

**Comment by astauffer** [comment]
![image](https://cloud.githubusercontent.com/assets/3934437/8604911/88644210-264f-11e5-8629-9f5bd2a2158a.png)
