### ISSUE TITLE
Redo the way workers connect to the DB 

### ISSUE THREAD

**Issue by chelm** [koopjs/koop-agol#45]
Currently the request workers rely on koop-pgcache, which means they only work with PostGIS. This is straightforward re-working on the way the workers are init'd. I think there will be two files in the `workers` dir: an `index.js` and `worker.js` file. The index will establish db and queue connections and the worker will expose methods for making requests.

**Comment by dmfenton** [comment]
going with a whole new worker structure in https://github.com/koopjs/koop-worker
