### ISSUE TITLE
Requesting returnCountOnly=false still returns count only

### ISSUE THREAD

**Issue by ajturner** [koopjs/koop-agol#52]
E.g. 

- http://opendata.arcgis.com/datasets/fb892b436a4e4627b620f923ea3a0797_0/FeatureServer/0/query?where=1%3D1&returnCountOnly=false&outFields=*&f=json
- vs. http://opendata.arcgis.com/datasets/fb892b436a4e4627b620f923ea3a0797_0/FeatureServer/0/query?where=1%3D1&outFields=*&f=json

**Comment by dmfenton** [comment]
This was fixed in: https://github.com/koopjs/koop/commit/cd8d27fa8bb779e43d03903bd6be66591021971d
