### ISSUE TITLE
Incorrect field types for percent values

### ISSUE THREAD

**Issue by ajturner** [koopjs/koop-agol#54]
[This query](http://opendata.arcgis.com/datasets/fb892b436a4e4627b620f923ea3a0797_0/FeatureServer/0/query?where=1%3D1&outFields=*&f=json) has many fields with `%`

The [metadata](http://opendata.arcgis.com/datasets/fb892b436a4e4627b620f923ea3a0797_0/FeatureServer/0) uses both  `esriFieldTypeString` and  `esriFieldTypeDate` in an odd pattern.

**Comment by dmfenton** [comment]
Resolved in https://github.com/koopjs/koop/commit/d38604233140f2044899f0bb57e98a69e5faa8e1
