### ISSUE TITLE
semver beta notation is off

### ISSUE THREAD

**Issue by ngoldman** [koopjs/koop-agol#80]
from http://semver.org:

`1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0`

so `2.0.1-beta.2`, not `2.0.1-beta-2`

current notation may not work gracefully with npm versioning.

**Comment by dmfenton** [comment]
Resolved ine9f50317ee438a3beb1b26682d86cdc750dfe14f
